### ISSUE TITLE
Automatic installation of needls failed

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#11]
If needls is not installed, a pop is offered to install it. The installation fails however with the following error.

```
Error: Command failed: /usr/local/bin/python -m pip uninstall "git+https://github.com/open-needs/open-needs-ide" -y
WARNING: Invalid requirement: 'git+https://github.com/open-needs/open-needs-ide' ignored - the uninstall command expects named requirements.
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")
```
For uninstallation should it be
```
pip uninstall open-needs-ide -y
```
instead of
```
pip uninstall "git+https://github.com/open-needs/open-needs-ide" -y
```

https://github.com/open-needs/open-needs-ide/blob/main/vscode_ext/src/extension.ts#L124

**Comment by danwos** [comment]
Fixed with https://github.com/open-needs/open-needs-ide/pull/10.
(Re)Installation should now work more stable.

But still based on the main branch and not a PyPi release. Next topic to do....
