### ISSUE TITLE
Open IDE cannot find needls

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#12]
If needls is installed as follows, the extension cannot find the needls server.
> pip install  "git+https​://github.com/open-needs/open-needs-ide"

needls v0.0.10

pip freeze returns
> needls @ git+https:​//github.com/open-needs/open-needs-ide@​802c74be5457d8e2b5c88d8a7ce5b92c394144c9

**Comment by danwos** [comment]
Should be solved with the current code on main.

The problem was a hardcoded check, that the VS Code extension wants needls 0.0.8.
Also the import of this version from python to the typescript code was a little buggy.
