### ISSUE TITLE
Support ${workspaceFolder} within settings

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#17]
Support ${workspaceFolder} within settings

Example:
```
  "needls.buildPath": "${workspaceFolder}/build",
  "needls.docsRoot": "${workspaceFolder}/docs",
```

**Comment by danwos** [comment]
Not sure if this is doable, as there seems to be no API available.

There are a lot of issues on the bug tracker of VS code for this:
https://github.com/microsoft/vscode/issues/70769

And 1-2 comments report for a workaround / self-implemented solution for selected vars.

So the extension could try to figure out the current workspace folder on its own and also replace `${workspaceFolder}`.
But only `${workspaceFolder}`, no other vars from https://code.visualstudio.com/docs/editor/variables-reference

**Comment by twodrops** [comment]
ok. restructuredText Extension seems to support it 
`"restructuredtext.confPath": "${workspaceFolder}"`
Maybe with the hacks you mentioned. 
I guess this is the most important one and shall do.

**Comment by danwos** [comment]
Ohh thanks for the hint.
I will take a look into their code to borrow some ideas :)

**Comment by danwos** [comment]
Possible solutions: 
* https://www.npmjs.com/package/vscode-variables
* `const currentWorkspaceFolderPath = vscode.workspace.getWorkspaceFolder(vscode.window.activeTextEditor.document.uri)?.uri.fsPath`

**Comment by danwos** [comment]
Must be tested in Docker container env. There seems to be some probs with VS Code dev containers.
Maybe the vr calculation does not work in docker.

**Comment by twodrops** [comment]
@danwos  This works now with 0.0.15. Thank you :)
