### ISSUE TITLE
Support relative path within settings

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#18]
I guess this is a known issue. Just thought of documenting it.

Support relative path within settings. The context shall be the workspace folder.

Example:
```
  "needls.buildPath": "build",
  "needls.docsRoot": "docs",
```

**Comment by danwos** [comment]
Could be also resolved by supporting `${workspaceFolder}` var from #17, or not?

**Comment by danwos** [comment]
I think `../` should get resolved inside an absolute path.

Internally I would also like to work with absolute paths only.
So the reading-code of configs and co. should deal with any kind of transformation from a templated-based, relative path to an absolute path.

We have too many players here (vs code, the vs code extension, and the needls server) and all of them may handle relative paths differently or have another working directory set.
Saying this, the python code gets only absolute paths :)

So for the moment, I will close this in favor of #17.
If we see real use cases, I have no problem reopening it.
