### ISSUE TITLE
Extension does not allow "undeclared" variables in conf.py

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#24]
Variables like "tags" in conf.py are resolved by Sphinx, but the extension does not resolve them and throws an undeclared variable error.

**Comment by danwos** [comment]
As Sphinx somehow injected this "tags" var during loading of the conf.py, it is not available during a "normal" import as Open-Needs IDE is doing it.

Maybe we can inject an empty "tags" var as well.
As long as the needed information (mostly needs_types) is not based on this value, it should be okay.

**Comment by danwos** [comment]
Closed in favor of #56.

So in the future there should be a small, clean "smaller_conf.py" file, which does not use any external information, which is normally injected by other programs when getting loaded (e.g. sphinx).
