### ISSUE TITLE
feature: support the needs role in MyST markdown files

### ISSUE THREAD

**Issue by arwedus** [open-needs/open-needs-ide#31]
MyST markdown supports almost all features of reStructuredText by special Markdown-compatible syntax.
Roles can be added using the syntax below:

```
This code addresses the {need}`REQ_MD_0001`.
```

which is equivalent to rST:

```
This code addresses the :need:`REQ_MD_0001`.
```

Open-Needs IDE shall parse markdown files and add code navigation links to the need-links found in Markdown files using the MyST-Markdown role syntax.

**Comment by haiyangToAI** [comment]
Issue moved to Sphinx-Needs.
