### ISSUE TITLE
Cursor jumps while updating VScode Settings

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#34]
There is a funny behavior under Windows when a VsCode Setting is edited and the next setting clicked, the cursor jumps back to the  first setting (maybe the "Update settings" runs in background). It takes several clicks till the second field can be edited. The behavior is also not always reproducible.

**Comment by danwos** [comment]
Interesting bug.
I can't reproduce this on my setup (Linux-based).

And I think this behavior is a bug in VS code, as Open-Needs IDE does not execute any code for this.
The settings fields are based on JSON configuration only.

On Linux, I have another bug, which deactivates my arrow keys left and right, after some not yet so clear events.
Only a restart helps. The same behavior I have on the MS Teams app.

Both tools MS Teams and VS Code are based on Electron.
So maybe Electron is also for this bug the problem.

I'm not sure, but I'm afraid that Open-Needs IDE can't do anything to solve this bug.

**Comment by danwos** [comment]
See to be general VS Code bug. Other settings are affected as well.
