### ISSUE TITLE
Needs loaded message could be nagging

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#35]
For debugging the message "Using needs from ..." is really good. For a typical user, this could be nagging to see the message for every save. Does it make sense to make it configurable/ make it available in some debug mode only?

**Comment by kapinnow** [comment]
great idea - would be even nice for the puzzled user (with helpful hints) to have an option similar to logging (with the known categories debug/info/warning/error)

**Comment by danwos** [comment]
You would say instead of showing the message directly as a pop-up on the screen, it goes to the Extension Log, which can be opened quite easily.

**Comment by twodrops** [comment]
@danwos Yes, I would write it to the extension log. For most users this is not of interest I guess to see it directly on the screen.
