### ISSUE TITLE
simple (automated) release test is missing

### ISSUE THREAD

**Issue by kapinnow** [open-needs/open-needs-ide#4]
A release test shall cover

* installation as an extension to the supported VSCode version(s) on the supported platforms and with the supported components (e.g. Python versions)
* usage of an suitable example project (e.g. from needs)
* walk through and check the main features
* uninstall

Optional: creation and use of a specific tutorial

**Comment by kapinnow** [comment]
Any hint on the way to develop this i.e. go with the [prebuilt mechanism](https://vscode-docs.readthedocs.io/en/latest/extensions/testing-extensions/ ) or with the [Selenium way](https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions#making_it_simple)?

**Comment by danwos** [comment]
No, I'm also new to VS Code extension development and have no suggestion.
For the beginning I would stay with the official proposals from microsoft for testing (if they meet our needs).

I also tried to find some extensions, to figure out how they do their testing.
https://github.com/topics/vscode-extension
But it looks like tests are not so common in the vscode-extension world.
But maybe we find a good one and can take their configuration for a first shot.

**Comment by danwos** [comment]
Tests-Framework got implemented for local debugging and on CI.
See the short documentation about it on https://open-needs.org/open-needs-ide/contribution.html#debugging-extension

So for lint and tests get now executed for needls (pytest, black) and vs code extension (Extension Host and eslint).
