### ISSUE TITLE
Python could not be found if only Python3 is available

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#42]
With Open-Needs IDE 0.0.15 the following error is raised in an environment where only python3 is installed.
> apt install python3

```
/bin/sh: 1: /usr/bin/python: not found
```

Creating a symlink for python manually or installing an additional packet to make python3 available as python everything worked.
> apt install python-is-python3

After python3 was made available as python, the extension asked for a confirmation of the python and added to settings. I hope this is also the expected behavior.

**Comment by danwos** [comment]
We have to check this, as I'm not sure where the `usr/bin/python` is coming from.
Normally asking the user for the python path and testing it, is our first step.
We will check...
