### ISSUE TITLE
If python cannot be found, extension complains about missing needls

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#43]
If the python cannot be found (for example, due to the problem as mentioned in #42), the extension complains about a missing/mismatched "open-needs-ls" version, although it is present. 

The error message is misleading and can be found only from the log that the real error is because of missing python.

Making the python version available again does not throw the missing needls error without any further action.

**Comment by danwos** [comment]
Detected this as well.
We will add a test for python only.

Thanks for the bug report.

**Comment by haiyangToAI** [comment]
Solved by fixing issue #42
