### ISSUE TITLE
empty pythonPath in templates and it is platform dependent

### ISSUE THREAD

**Issue by kapinnow** [open-needs/open-needs-ide#48]
The python path should be defined in open-needs-ide\test-envs\setup_envs.py but it is empty. 
Moreover it is platform dependent i.e. under Windows s.th. like 

      "${workspaceFolder}\\.venv\\Scripts\\python.exe" 

is expected while under Linux one would like to see

      "${workspaceFolder}\\.venv\\bin\\python.exe"

**Comment by haiyangToAI** [comment]
Hi,

This project is not maintained anymore and is archived.

All the current features have been moved to project Sphinx-Needs: https://github.com/useblocks/sphinxcontrib-needs/tree/master/sphinx_needs/lsp. The features will be automatically detected by VsCode extension reStructuredText: https://github.com/vscode-restructuredtext/vscode-restructuredtext in your Sphinx-Needs project.

Further features development will be done inside the Sphinx-Needs project.

Thanks.
