### ISSUE TITLE
autoBuild is used in the code but undefined in package.json

### ISSUE THREAD

**Issue by kapinnow** [open-needs/open-needs-ide#50]
Within extension.ts in function make_needs the autoBuild field is read and should be used

```
// only build if auto build setting is switched on
	const auto_build = workspace.getConfiguration('needls').get('autoBuild');
	if (auto_build === false) {
		return;
	}
```

but it is not define in the package.json definition and not incorporated in any settings.json as well as in the documentation.

Options: remove or define.

**Comment by haiyangToAI** [comment]
Hi,

This project is not maintained anymore and is archived.

All the current features have been moved to project Sphinx-Needs: https://github.com/useblocks/sphinxcontrib-needs/tree/master/sphinx_needs/lsp. The features will be automatically detected by VsCode extension reStructuredText: https://github.com/vscode-restructuredtext/vscode-restructuredtext in your Sphinx-Needs project.

Further features development will be done inside the Sphinx-Needs project.

Thanks.
