### ISSUE TITLE
Needls features of Version 0.0.17 not yet fully working, will test and fix all of them soon 

### ISSUE THREAD

**Issue by haiyangToAI** [open-needs/open-needs-ide#62]
Hi @twodrops @danwos ,

We just released a new version 0.0.17, which improved confPath, fixed pygls module not found issue and certain needls feature like hover. However, not all the needls features are working yet.

I will test and fix all the rest tomorrow and will release a new version 0.0.18.

Sorry for the inconvenience in the moment.

**Comment by twodrops** [comment]
@danwos @haiyangToAI I tested the version and all the basic usecases works. Thanks a lot!
