### ISSUE TITLE
Settings are undefined for the first run after installation

### ISSUE THREAD

**Issue by twodrops** [open-needs/open-needs-ide#66]
After the extension is installed, the first build always fails with the following error.

>Update settings...
Docs root: undefined
Needs file: undefined/build/needs/needs.json
Something is wrong with Docs root: undefined -> Docs root directory not found: undefined

## Steps to reproduce

* Have a clean workspace
* Install the extension and language server
* Open an rST file, edit and save
* Error
* Do a second edit and save
* No Error

### Log when no error
> Update settings...
Docs root: /workspace
Needs file: /workspace/build/needs/needs.json
confPath not configured. Using default conf.py under docs root.
Declared need types: {<----REMOVED CONTENTS FOR PUBLISH--->}
Loaded 8 needs from needs.json: [<----REMOVED CONTENTS FOR PUBLISH--->]
Using needs in: /workspace/build/needs/needs.json

**Comment by haiyangToAI** [comment]
Hi,

This project is not maintained anymore and is archived.

All the current features have been moved to project Sphinx-Needs: https://github.com/useblocks/sphinxcontrib-needs/tree/master/sphinx_needs/lsp. The features will be automatically detected by VsCode extension reStructuredText: https://github.com/vscode-restructuredtext/vscode-restructuredtext in your Sphinx-Needs project.

Further features development will be done inside the Sphinx-Needs project.

Thanks.
