### ISSUE TITLE
Defining Snippet templates for different need types

### ISSUE THREAD

**Issue by MohSam1** [open-needs/open-needs-ide#69]
I have a usecase where I want to have different snippets for different need types, 
Eg:

``` python
# In conf.py

# List of needs types
needs_types = [
    dict(directive='need_1',     title='Type 1', style='artifact' ),
    dict(directive='need_2',      title='Type 2', style='rectangle'),
 ]
```
After need_1 and node_2 code snippets are selected from drop down

``` rst
.. need_1:: title
   :id: XYZ_54e53d79
   :status: open
   :attribute1: 

   content.

.. need_2:: title
   :id: ABC_1278e567
   :status: open
   :attribute2: 

   content.

```

Is this possible ?

**Comment by haiyangToAI** [comment]
Hi @MohSam1,

This project is not maintained anymore and is archived.

All the current features have been moved to project Sphinx-Needs: https://github.com/useblocks/sphinxcontrib-needs/tree/master/sphinx_needs/lsp. The features will be automatically detected by VsCode extension reStructuredText: https://github.com/vscode-restructuredtext/vscode-restructuredtext  in your Sphinx-Needs project. 

Further features development will be done inside the Sphinx-Needs project. 

I will move this issue to there. Please in the future open issues in the Sphinx-Needs project.

Thanks.
